<a href="https://www.kaggle.com/code/fabinahian/numpy-basics?scriptVersionId=130722594" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Importing Libraries

In [1]:
import sys
import numpy as np

# Basic NumPY Arrays

## Generating & Store Arrays

In [2]:
# This is how an array is generated using NumPy

np.array ([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
# This is how you can generate AND store an array inside a variable using NumPy

a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11])

## Extracting Values from Arrays

In [4]:
# This is how you can extract values from the arrays
# a = np.array([1,2,3,4,5,6])

a[0]

1

In [5]:
# a = np.array([1,2,3,4,5,6])

a[1]

2

In [6]:
# a = np.array([1,2,3,4,5,6])

a[0],a[1]

(1, 2)

In [7]:
# a = np.array([1,2,3,4,5,6])

a[0:]

array([1, 2, 3, 4, 5, 6])

In [8]:
# a = np.array([1,2,3,4,5,6])

a[1:4]

array([2, 3, 4])

In [9]:
# a = np.array([1,2,3,4,5,6])

a[1:-1]

array([2, 3, 4, 5])

In [10]:
# a = np.array([1,2,3,4,5,6])

a[::2]

array([1, 3, 5])

In [11]:
# b = np.array([7,8,9,10,11])

# multi indexing

b[0], b[2], b[-1]

(7, 9, 11)

In [12]:
# b = np.array([7,8,9,10,11])

# multi indexing

b[[0,2,-1]]

array([ 7,  9, 11])

In [13]:
# multi indexing

a[0], b[0]

(1, 7)

# Array Types

NumPy can automatically pick a data type (eg int, float etc) but you can also specify to declare your own preference



In [14]:
a


array([1, 2, 3, 4, 5, 6])

In [15]:
a.dtype


dtype('int64')

In [16]:
c = np.array([0.0, 1, 5.2, 7, 8])

c.dtype

dtype('float64')

In [17]:
# Declaring the type to be float even though the values are int

d = np.array([1,2,3,4], dtype = float)

d.dtype

dtype('float64')

In [18]:
# You can also change the type from int64 to int8 --> smaller integers for better performance

np.array([1,2,3,4,5,6,7,8,9], dtype = np.int8)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

# Dimensions & Shapes

We can create multi-dimensional arrays in NumPy

## 2 Dimensional Arrays

In [19]:
# 2 dimensional arrays shown below: 2 rows & 3 columns

A = np.array ([[1,2,3],[4,5,6]]) # You can define it in this way
 
AA = np.array ([[10,11,12],       # You can define it in this way as well
              [13,14,15]])

In [20]:
A.shape # (row, column)

(2, 3)

In [21]:
A.ndim # Number of dimensions : here, 1 vertical & 1 horizontal

2

In [22]:
A.size # Total number of elements


6

## 3 Dimensional Arrays