<a href="https://www.kaggle.com/code/fabinahian/numpy-exercises?scriptVersionId=130790904" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# NumPy exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.23.5




# Array creation

## Create a numpy array of size 10, filled with zeros.

In [2]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


## Create a numpy array with values ranging from 10 to 49

In [3]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

##  Create a numpy matrix of 2*2 integers, filled with ones.

In [4]:
np.ones([2,2], dtype=int)


array([[1, 1],
       [1, 1]])



## Create a numpy matrix of 3*2 float numbers, filled with ones.

In [5]:
np.ones([3,2], dtype = float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])



## Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [6]:
x = np.arange (4, dtype = int)

x

array([0, 1, 2, 3])

In [7]:
np.ones_like(x)

array([1, 1, 1, 1])

## Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [8]:
x = np.array ([
    [1,2,3],
    [4,5,6]
], dtype = int)

x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

##  Create a numpy matrix of 4*4 integers, filled with fives.

In [10]:
np.ones([4,4], dtype =int) * 5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

## Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [11]:
x = np.array([[2,3], [4,5]], dtype = int)

x

array([[2, 3],
       [4, 5]])

In [12]:
np.ones_like(x) *7

array([[7, 7],
       [7, 7]])

## Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [13]:
np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Create a numpy array, filled with 3 random integer values between 1 and 10.

In [14]:
np.random.randint(10, size=3)

array([5, 8, 2])

## Create a 3\*3\*3 numpy matrix, filled with random float values.

In [15]:
np.random.randn(3,3,3)

array([[[ 0.83689761, -0.91882903,  1.47114595],
        [ 0.11991367,  1.05280409, -0.99672551],
        [ 0.54021133, -1.19583261, -1.08365564]],

       [[ 0.32202788, -1.52622098,  0.16018525],
        [-0.27888503,  1.60704291,  1.48146776],
        [ 2.41360079, -0.55052788, -0.40431136]],

       [[-0.67381247, -0.11674828, -0.47735053],
        [ 0.96919488,  0.13786622, -0.49635284],
        [-1.69412354,  2.50791281, -1.21131968]]])

## Given the X python list convert it to an Y numpy array

In [16]:
x = [1,2,3,4,5,6,7]
print(x, type(x))

y = np.array(x)
print(y, type(y))

[1, 2, 3, 4, 5, 6, 7] <class 'list'>
[1 2 3 4 5 6 7] <class 'numpy.ndarray'>


## Given the X numpy array, make a copy and store it on Y.

In [17]:
x = np.array([1,2,3], dtype=int)
print(x, id(x))

y = np.copy(x)
print(y, id(y))

[1 2 3] 133225991377840
[1 2 3] 133225991375824


## Create a numpy array with numbers from 1 to 10

In [18]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Create a numpy array with the odd numbers between 1 to 10

In [19]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

## Create a numpy array with numbers from 1 to 10, in descending order.

In [20]:
np.arange(1,11)[::-1]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [21]:
np.arange(9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Show the memory size of the given Z numpy matrix

In [22]:
z = np.zeros([10,10])

print("%d bytes" %(z.size * z.itemsize))

800 bytes


# Array indexation


## Given the X numpy array, show it's first element

In [23]:
x = np.arange(1,10)

print(x)
print(x[0])

[1 2 3 4 5 6 7 8 9]
1


## Given the X numpy array, show it's last element

In [24]:
x = np.arange(1,10)

print(x)
print(x[-1])

[1 2 3 4 5 6 7 8 9]
9


## Given the X numpy array, show it's first three elements

In [25]:
x = np.arange(1,6)

print(x)
print(x[:3])

[1 2 3 4 5]
[1 2 3]


## Given the X numpy array, show all middle elements

In [26]:
x = np.arange(5,10)

print(x)
print(x[1:-1])

[5 6 7 8 9]
[6 7 8]


## Given the X numpy array, show the elements in reverse position

In [27]:
x = np.arange(1,11)

print(x)
print(x[::-1])

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


## Given the X numpy array, show the elements in an odd position

In [28]:
x = np.arange(1,12)
print(x[::2])


[ 1  3  5  7  9 11]


## Given the X numpy matrix, show the first row elements

In [29]:
x = np.identity(3)
print(x)
print(" ")
print("first row: ", x[0])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
first row:  [1. 0. 0.]


## Given the X numpy matrix, show the last row elements

In [30]:
x = np.identity(3)
print(x)
print(" ")
print("last row: ", x[-1])


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
last row:  [0. 0. 1.]


## Given the X numpy matrix, show the first element on first row

In [31]:
x = np.eye(4, dtype=int)

print(x)
print(" ")
print("firt element: ",x[0,0]) # row= 0, column = 0


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
 
firt element:  1


## Given the X numpy matrix, show the last element on last row

In [32]:
x = np.eye(4, dtype=int)

print(x)
print(" ")
print("last element: ",x[-1,-1])

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
 
last element:  1


## Given the X numpy matrix, show the middle row elements

In [33]:
x = np.eye(4, dtype=int)

print(x)
print(" ")
print("middle rows: ",x[1:-1,1:-1]) 


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
 
middle rows:  [[1 0]
 [0 1]]


## Given the X numpy matrix, show the first two elements on the first two rows

In [34]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(x)
print(" ")
print(x[0:2,0:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[[1 2]
 [4 5]]


## Given the X numpy matrix, show the last two elements on the last two rows

In [35]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(x[1:,1:])

[[5 6]
 [8 9]]



## Array manipulation


## Convert the given integer numpy array to float

In [36]:
x= [1,2,3,4,5]

np.array(x,float)


array([1., 2., 3., 4., 5.])

## Reverse the given numpy array (first element becomes last)

In [37]:
x = np.arange(1,6)

print(x[::-1])


[5 4 3 2 1]


## Order (sort) the given numpy array

In [38]:
x = [6,2,3,8,-10,70]

x.sort()
x

[-10, 2, 3, 6, 8, 70]

## Given the X numpy array, set the fifth element equal to 1

In [39]:
x = [6,2,3,8,-10,70]

x[4] = 1

x


[6, 2, 3, 8, 1, 70]

## Given the X numpy array, change the 50 with a 40

In [40]:
x = [6,2,3,50,-1,70]

x[3] = 40

x

[6, 2, 3, 40, -1, 70]

## Given the X numpy matrix, change the last row with all 1

In [41]:
x = np.arange(9).reshape(3,3)

print(x)
print(" ")

x[2:,:]=1
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[0 1 2]
 [3 4 5]
 [1 1 1]]


## Given the X numpy matrix, change the last item on the last row with a 0

In [42]:
x = np.arange(9).reshape(3,3)

print(x)
print(" ")

x[-1,-1]= 0 
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[0 1 2]
 [3 4 5]
 [6 7 0]]


## Given the X numpy matrix, add 5 to every element

In [43]:
x = np.arange(9).reshape(3,3)

print(x)
print(" ")

x += 5 
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]



# Boolean arrays _(also called masks)_



## Given the X numpy array, make a mask showing negative elements

In [44]:
x = np.array([1,2,3,-4,-5,-6,7,8])

print(x)
print(" ") 
print("Negative values: ",x[x<0])


[ 1  2  3 -4 -5 -6  7  8]
 
Negative values:  [-4 -5 -6]


## Given the X numpy array, get numbers higher than 5

In [45]:
x = np.array([1,2,3,4,5,6,7,8,9,10])

print("Greater than 5: ", x[x>5])

Greater than 5:  [ 6  7  8  9 10]


## Given the X numpy array, get numbers higher than the elements mean

In [46]:
x = np.array([1,2,3,40,5,6,7,8,9,10])

print("mean: ", x.mean())
print("Greater than the mean: ", x[x>x.mean()])


mean:  9.1
Greater than the mean:  [40 10]


## Given the X numpy array, get numbers equal to 2 or 10

In [47]:
x = np.array([1,2,3,40,5,6,7,8,9,10])

print("Equal to 2 or 10: ", x[(x==2) | (x==10)])

Equal to 2 or 10:  [ 2 10]



# Logic functions


## Given the X numpy array, return True if none of its elements is zero

In [48]:
x = np.array([1,2,3,4])

x.all()


True

## Given the X numpy array, return True if any of its elements is zero

In [49]:
x = np.array([2,3,4,5,6,7,0])

x.any()

True


# Summary statistics

### Given the X numpy array, show the sum of its elements

In [50]:
x = np.array([1,3,2,43,5,35,9])

x.sum()

98

## Given the X numpy array, show the mean value of its elements

In [51]:
x = np.array([1,3,2,43,5,35,9])

x.mean()

14.0

## Given the X numpy matrix, show the sum of its columns

In [52]:
x = np.arange(9).reshape(3,3)

print(x)
print(" ")
print(x.sum(axis = 0)) # note: axis=0 columns; axis=1 rows
 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[ 9 12 15]


## Given the X numpy matrix, show the mean value of its rows

In [53]:
x = np.arange(9).reshape(3,3)

print(x)
print(" ")
print(x.mean(axis = 1)) # note: axis=0 columns; axis=1 rows
 


[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[1. 4. 7.]


## Given the X numpy array, show the max value of its elements

In [54]:
x = np.arange(10,19).reshape(3,3)

print(x)
print(" ")
print(x.max()) # note: axis=0 columns; axis=1 rows
 


[[10 11 12]
 [13 14 15]
 [16 17 18]]
 
18
