<a href="https://www.kaggle.com/code/fabinahian/numpy-basics?scriptVersionId=130725911" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Importing Libraries

In [1]:
import sys
import numpy as np

# Generating & Storing Arrays

In [2]:
# This is how an array is generated using NumPy

np.array ([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
# This is how you can generate AND store an array inside a variable using NumPy

a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11])

# Slicing & Indexing Arrays

In [4]:
# This is how you can extract values from the arrays
# a = np.array([1,2,3,4,5,6])

a[0]

1

In [5]:
# a = np.array([1,2,3,4,5,6])

a[1]

2

In [6]:
# a = np.array([1,2,3,4,5,6])

a[0],a[1]

(1, 2)

In [7]:
# a = np.array([1,2,3,4,5,6])

a[0:]

array([1, 2, 3, 4, 5, 6])

In [8]:
# a = np.array([1,2,3,4,5,6])

a[1:4]

array([2, 3, 4])

In [9]:
# a = np.array([1,2,3,4,5,6])

a[1:-1]

array([2, 3, 4, 5])

In [10]:
# a = np.array([1,2,3,4,5,6])

a[::2]

array([1, 3, 5])

In [11]:
# b = np.array([7,8,9,10,11])

# multi indexing

b[0], b[2], b[-1]

(7, 9, 11)

In [12]:
# b = np.array([7,8,9,10,11])

# multi indexing

b[[0,2,-1]]

array([ 7,  9, 11])

In [13]:
# multi indexing

a[0], b[0]

(1, 7)

# Array Types

NumPy can automatically pick a data type (eg int, float etc) but you can also specify to declare your own preference



In [14]:
a


array([1, 2, 3, 4, 5, 6])

In [15]:
a.dtype


dtype('int64')

In [16]:
c = np.array([0.0, 1, 5.2, 7, 8])

c.dtype

dtype('float64')

In [17]:
# Declaring the type to be float even though the values are int

d = np.array([1,2,3,4], dtype = float)

d.dtype

dtype('float64')

In [18]:
# You can also change the type from int64 to int8 --> smaller integers for better performance

np.array([1,2,3,4,5,6,7,8,9], dtype = np.int8)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

# Dimensions & Shapes

We can create multi-dimensional arrays in NumPy

# 2 Dimensional Arrays

In [19]:
# 2 dimensional arrays shown below: 2 rows & 3 columns

A = np.array ([[1,2,3],[4,5,6]]) # You can define it in this way
 
AA = np.array ([[10,11,12],       # You can define it in this way as well
              [13,14,15]])

In [20]:
A.shape # (row, column)

(2, 3)

In [21]:
A.ndim # Number of dimensions : here, 1 vertical & 1 horizontal

2

In [22]:
A.size # Total number of elements


6

# 3 Dimensional Arrays

In [23]:
B = np.array ([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [24]:
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
B.shape

(2, 2, 3)

In [26]:
B.ndim

3

In [27]:
B.size

12

# Slicing & Indexing for Matrices (Multi-Dimensional Arrays)

In [28]:
# Square Matrix

A = np.array([
    [1,2,3],  # row 0
    [4,5,6],  # row 1
    [7,8,9]   # row 2 
])

In [29]:
A[1] # Gets row: 1

array([4, 5, 6])

In [30]:
A[1][0] # Gets the element of row: 1 and column: 0

4

In [31]:
# This method also allows for slicing (shown in the next cell)

A [ 1,0 ] # Gets the element of row: 1 and column: 0

4

In [32]:
A [ : , :2] # Gets all rows but only upto 2 for column level

array([[1, 2],
       [4, 5],
       [7, 8]])

In [33]:
# We can insert rows

A[1] = np.array([10,10,10])

A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [34]:
# We can also insert rather simply while letting NumPy do the work on the dimension

A[2] = 99
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary Statistics For Arrays

In [35]:
a = np.array([1,2,3,4,5])

In [36]:
a.sum()

15

In [37]:
a.mean()

3.0

In [38]:
a.std()

1.4142135623730951

In [39]:
a.var()

2.0

# Summary Statistics For Matrices

In [40]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [41]:
A.sum()

21

In [42]:
A.mean()

3.5

In [43]:
A.std()

1.707825127659933

In [44]:
A.var()

2.9166666666666665

In [45]:
# You can also use all these functions with only rows or only columns by using axises

A.sum (axis = 0 ) # Gets sum of all individual columns : axis = 0 

array([5, 7, 9])

In [46]:
A.sum (axis = 1 ) # Gets sum of all individual rows : axis = 1

# You can keep increasing the value of "axis" if you work with more dimensions

array([ 6, 15])