# Source: [Data Analysis with Python](https://www.freecodecamp.org/learn/data-analysis-with-python/)

# NumPy exercises


In [141]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.23.5




# Array creation

## Create a numpy array of size 10, filled with zeros.

In [142]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


## Create a numpy array with values ranging from 10 to 49

In [143]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

##  Create a numpy matrix of 2*2 integers, filled with ones.

In [144]:
np.ones([2,2], dtype=int)


array([[1, 1],
       [1, 1]])



## Create a numpy matrix of 3*2 float numbers, filled with ones.

In [ ]:
np.ones([3,2], dtype = float)



## Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [ ]:
x = np.arange (4, dtype = int)

x

In [ ]:
np.ones_like(x)

## Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [ ]:
x = np.array ([
    [1,2,3],
    [4,5,6]
], dtype = int)

x

In [ ]:
np.zeros_like(x)

##  Create a numpy matrix of 4*4 integers, filled with fives.

In [ ]:
np.ones([4,4], dtype =int) * 5


## Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [ ]:
x = np.array([[2,3], [4,5]], dtype = int)

x

In [ ]:
np.ones_like(x) *7

## Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [ ]:
np.eye(3)
np.identity(3)

## Create a numpy array, filled with 3 random integer values between 1 and 10.

In [ ]:
np.random.randint(10, size=3)

## Create a 3\*3\*3 numpy matrix, filled with random float values.

In [ ]:
np.random.randn(3,3,3)

## Given the X python list convert it to an Y numpy array

In [ ]:
x = [1,2,3,4,5,6,7]
print(x, type(x))

y = np.array(x)
print(y, type(y))

## Given the X numpy array, make a copy and store it on Y.

In [ ]:
x = np.array([1,2,3], dtype=int)
print(x, id(x))

y = np.copy(x)
print(y, id(y))

## Create a numpy array with numbers from 1 to 10

In [ ]:
np.arange(1,11)

## Create a numpy array with the odd numbers between 1 to 10

In [ ]:
np.arange(1,11,2)

## Create a numpy array with numbers from 1 to 10, in descending order.

In [ ]:
np.arange(1,11)[::-1]


## Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [ ]:
np.arange(9).reshape(3,3)


## Show the memory size of the given Z numpy matrix

In [ ]:
z = np.zeros([10,10])

print("%d bytes" %(z.size * z.itemsize))

# Array indexation


## Given the X numpy array, show it's first element

In [ ]:
x = np.arange(1,10)

print(x)
print(x[0])

## Given the X numpy array, show it's last element

In [ ]:
x = np.arange(1,10)

print(x)
print(x[-1])

## Given the X numpy array, show it's first three elements

In [ ]:
x = np.arange(1,6)

print(x)
print(x[:3])

## Given the X numpy array, show all middle elements

In [ ]:
x = np.arange(5,10)

print(x)
print(x[1:-1])

## Given the X numpy array, show the elements in reverse position

In [ ]:
x = np.arange(1,11)

print(x)
print(x[::-1])

## Given the X numpy array, show the elements in an odd position

In [ ]:
x = np.arange(1,12)
print(x[::2])


## Given the X numpy matrix, show the first row elements

In [ ]:
x = np.identity(3)
print(x)
print(" ")
print("first row: ", x[0])

## Given the X numpy matrix, show the last row elements

In [ ]:
x = np.identity(3)
print(x)
print(" ")
print("last row: ", x[-1])


## Given the X numpy matrix, show the first element on first row

In [149]:
x = np.eye(4, dtype=int)

print(x)
print(" ")
print("firt element: ",x[0,0]) # row= 0, column = 0


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
 
firt element:  1


## Given the X numpy matrix, show the last element on last row

In [150]:
x = np.eye(4, dtype=int)

print(x)
print(" ")
print("last element: ",x[-1,-1])

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
 
last element:  1


## Given the X numpy matrix, show the middle row elements

In [152]:
x = np.eye(4, dtype=int)

print(x)
print(" ")
print("middle rows: ",x[1:-1,1:-1]) 


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
 
middle rows:  [[1 0]
 [0 1]]


## Given the X numpy matrix, show the first two elements on the first two rows

In [154]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(x)
print(" ")
print(x[0:2,0:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[[1 2]
 [4 5]]


## Given the X numpy matrix, show the last two elements on the last two rows

In [158]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(x[1:,1:])

[[5 6]
 [8 9]]



## Array manipulation


## Convert the given integer numpy array to float

In [160]:
x= [1,2,3,4,5]

np.array(x,float)


array([1., 2., 3., 4., 5.])

## Reverse the given numpy array (first element becomes last)

In [162]:
x = np.arange(1,6)

print(x[::-1])


[5 4 3 2 1]


## Order (sort) the given numpy array

In [168]:
x = [6,2,3,8,-10,70]

x.sort()
x

[-10, 2, 3, 6, 8, 70]

## Given the X numpy array, set the fifth element equal to 1

In [170]:
x = [6,2,3,8,-10,70]

x[4] = 1

x


[6, 2, 3, 8, 1, 70]

## Given the X numpy array, change the 50 with a 40

In [176]:
x = [6,2,3,50,-1,70]

x[3] = 40

x

[6, 2, 3, 40, -1, 70]

## Given the X numpy matrix, change the last row with all 1

In [186]:
x = np.arange(9).reshape(3,3)

print(x)
print(" ")

x[2:,:]=1
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[0 1 2]
 [3 4 5]
 [1 1 1]]


## Given the X numpy matrix, change the last item on the last row with a 0

In [187]:
x = np.arange(9).reshape(3,3)

print(x)
print(" ")

x[-1,-1]= 0 
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[0 1 2]
 [3 4 5]
 [6 7 0]]


## Given the X numpy matrix, add 5 to every element

In [188]:
x = np.arange(9).reshape(3,3)

print(x)
print(" ")

x += 5 
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]



# Boolean arrays _(also called masks)_



## Given the X numpy array, make a mask showing negative elements

In [198]:
x = np.array([1,2,3,-4,-5,-6,7,8])

print(x)
print(" ") 
print("Negative values: ",x[x<0])


[ 1  2  3 -4 -5 -6  7  8]
 
Negative values:  [-4 -5 -6]


## Given the X numpy array, get numbers higher than 5

In [199]:
x = np.array([1,2,3,4,5,6,7,8,9,10])

print("Greater than 5: ", x[x>5])

Greater than 5:  [ 6  7  8  9 10]


## Given the X numpy array, get numbers higher than the elements mean

In [205]:
x = np.array([1,2,3,40,5,6,7,8,9,10])

print("mean: ", x.mean())
print("Greater than the mean: ", x[x>x.mean()])


mean:  9.1
Greater than the mean:  [40 10]


## Given the X numpy array, get numbers equal to 2 or 10

In [208]:
x = np.array([1,2,3,40,5,6,7,8,9,10])

print("Equal to 2 or 10: ", x[(x==2) | (x==10)])

Equal to 2 or 10:  [ 2 10]


array([ 2, 10])


# Logic functions


## Given the X numpy array, return True if none of its elements is zero

In [214]:
x = np.array([1,2,3,4])

x.all()


True

## Given the X numpy array, return True if any of its elements is zero

In [215]:
x = np.array([2,3,4,5,6,7,0])

x.any()

True


# Summary statistics

### Given the X numpy array, show the sum of its elements

In [216]:
x = np.array([1,3,2,43,5,35,9])

x.sum()

98

## Given the X numpy array, show the mean value of its elements

In [217]:
x = np.array([1,3,2,43,5,35,9])

x.mean()

14.0

## Given the X numpy matrix, show the sum of its columns

In [220]:
x = np.arange(9).reshape(3,3)

print(x)
print(" ")
print(x.sum(axis = 0)) # note: axis=0 columns; axis=1 rows
 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[ 9 12 15]


## Given the X numpy matrix, show the mean value of its rows

In [221]:
x = np.arange(9).reshape(3,3)

print(x)
print(" ")
print(x.mean(axis = 1)) # note: axis=0 columns; axis=1 rows
 


[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[1. 4. 7.]


## Given the X numpy array, show the max value of its elements

In [224]:
x = np.arange(10,19).reshape(3,3)

print(x)
print(" ")
print(x.max()) # note: axis=0 columns; axis=1 rows
 


[[10 11 12]
 [13 14 15]
 [16 17 18]]
 
18
